### ISSUE TITLE
Public release version (1.0.0.GA)

### ISSUE THREAD

**Issue by dulanov** [Infinitape/etherjar#59]
- [ ] Maven & gradle solidity plugins (#56)
- [ ] Spring Boot starter satellite project (#57)
- [ ] [EIP-20](https://github.com/ethereum/eips/issues/20) based pet-token dApp reference impl. (#44)
- [ ] Add a Java API badge (`javadoc.io/doc/io.infinitape/etherjar-web3`, #54)
- [ ] Public on maven central (`io.infinitape`)
- [ ] Bump version to `1.0.0.GA` (after all else)

Expected at the end of 2017.
